const ROOT_HEADER = document.getElementById('header');
const ROOT_ABOUT = document.getElementById('about');
const ROOT_NUMBERS = document.getElementById('numbers');
const ROOT_LINE = document.getElementById('line');
const ROOT_TEACHERS = document.getElementById('teachers');
const ROOT_CURSES = document.getElementById('curses');
const ROOT_TIMETABLE=document.getElementById('timetable')
const ROOT_REVIEWS = document.getElementById('reviews');
const ROOT_FAQ = document.getElementById('faq');
const ROOT_ACTION = document.getElementById('action');
const ROOT_FOOTER = document.getElementById('footer');
const ROOT_PROGRAM = document.getElementById('program');
const ROOT_LERN = document.getElementById('lern');
const ROOT_SPECIALIST = document.getElementById('specialist');