# Generated by Django 3.1.1 on 2021-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка на картинку')),
            ],
        ),
    ]
